### ISSUE TITLE
When redis is down, the init function does not resolve/reject its promise.

### ISSUE THREAD

**Issue by tWinE-xx** [flywheelsports/fwsp-hydra#34]
When redis is down, the init function does not resolve/reject its promise.
index.js line 125  ->  this.redisdb.select(HYDRA_REDIS_DB, (err, result) => {
never gets into callback somehow when redis is down

**Comment by cjus** [comment]
Thanks for this issue. Hydra implements Redis connection retries here: https://github.com/flywheelsports/fwsp-hydra/blob/master/index.js#L197

The behavior is that your application will exit if an underlying connection can't be established with Redis. The reconnection logic can take up to a minute before terminating. 

That said, you're correct about the init promise not rejecting in this situation. We're taking a closer look at this now.

**Comment by cjus** [comment]
closed by #35
