### ISSUE TITLE
Update Websockets Messaging Documentation 

### ISSUE THREAD

**Issue by miksansegundo** [flywheelsports/fwsp-hydra#43]
Hi there,

seems like the docs about Websockets Messaging is not updated, for example the use of the 
 method **sendReplyMessage**.

I have a question, the only way to know If a message is coming from one service of other is checking the **from** property of the message, right?

**Comment by cjus** [comment]
@miksansegundo The documentation could certainly use some updates. What did you feel was missing or out of date in the section that covers sendMessageReply? https://github.com/flywheelsports/fwsp-hydra/blob/master/documentation.md#inter-service-messaging

Yes, checking the from field is how you determine where a message came from and the `via` field can be useful as well. See: https://github.com/cjus/umf/blob/master/umf.md#Via%20-%20sent%20through

**Comment by miksansegundo** [comment]
@cjus Thanks for your answer. 
About the sendReplyMessage method, I have reviewed it and it's well explained and it's working so really don't know what happened that day I read the docs. lol Nevermind :)
