### ISSUE TITLE
redis url does not work

### ISSUE THREAD

**Issue by k33g** [flywheelsports/fwsp-hydra#44]
Hello,

With `fwsp-hydra-express` I can  set the url of redis like this

```
    "redis": {
      "url": "redis://:mypasswd@www.somewhere.com",
      "port": 3046,
      "db": 15
    }
```

and it's ok

but with the `fwsp-hydra` it's impossible to connect to the redis db

**Comment by emadum** [comment]
Hi @k33g, are you using the latest version of fwsp-hydra? Do you get any error message? I'm unable to reproduce in this in hydra 0.14.3.

**Comment by k33g** [comment]
Hi @emadum you're right, I tried with hydra 0.14.3. and 0.14.4 and it's ok (I used an old project)
sorry for that and thank you for the answer
